// Generated by CoffeeScript 2.7.0
(function() {
  var Canvas, Linkage, PythagFolding, PythagProof, TwelveTriangles, append, get_div;

  get_div = function(selector) {
    return document.querySelector(selector);
  };

  append = function(div, html) {
    return div.innerHTML += html;
  };

  Canvas = function(div, id, width = 600, height = 300) {
    var canvas, canvas_html, ctx, lineTo, moveTo;
    canvas_html = `<canvas id='${id}' width='${width}' height='${height}' style='border: 1px blue solid'>
</canvas>`;
    append(div, canvas_html);
    canvas = document.getElementById(id);
    ctx = canvas.getContext("2d");
    moveTo = function(point) {
      var x, y;
      [x, y] = point;
      return ctx.moveTo(Math.floor(x), Math.floor(y));
    };
    lineTo = function(point) {
      var x, y;
      [x, y] = point;
      return ctx.lineTo(Math.floor(x), Math.floor(y));
    };
    return {
      clear: function() {
        return canvas.width = width;
      },
      segment: function(color, point1, point2) {
        ctx.strokeStyle = color;
        ctx.lineWidth = 2;
        ctx.beginPath();
        moveTo(point1);
        lineTo(point2);
        ctx.stroke();
        return ctx.closePath();
      },
      draw_polygon: function(color, point1, ...more_points) {
        var j, len, point;
        ctx.fillStyle = color;
        ctx.beginPath();
        moveTo(point1);
        for (j = 0, len = more_points.length; j < len; j++) {
          point = more_points[j];
          lineTo(point);
        }
        lineTo(point1);
        ctx.fill();
        return ctx.closePath();
      },
      outline_triangle: function(color, point1, point2, point3) {
        ctx.strokeStyle = color;
        ctx.lineWidth = 1;
        ctx.beginPath();
        moveTo(point1);
        lineTo(point2);
        lineTo(point3);
        lineTo(point1);
        ctx.stroke();
        return ctx.closePath();
      }
    };
  };

  Linkage = function() {
    var a, b, button, canvas, dh, draw, dt, h, height, path1, path2, path3, path4, paused, recording, rescale, width, x_offset, y_distort;
    width = 700;
    height = 450;
    x_offset = 0;
    y_distort = 0;
    rescale = function(point) {
      var x, y;
      [x, y] = point;
      x += x_offset;
      y *= y_distort;
      return [x * 20 + 100, height - y * 20 - 10];
    };
    canvas = Canvas(get_div("#linkage"), "linkage_canvas", width, height);
    a = 17;
    b = 5;
    h = 0;
    dh = 0.05;
    dt = 2;
    paused = false;
    recording = true;
    path1 = [];
    path2 = [];
    path3 = [];
    path4 = [];
    draw = function() {
      var A, B, C, D, E, Y, c, cos, d, e, i, j, k, len, path, pos_neg, ref, ref1, rotate, segment, show, sin;
      if (paused) {
        return;
      }
      canvas.clear();
      c = Math.sqrt(a * a - b * b);
      d = Math.sqrt(c * c + h * h); // distance from A to center of rhombus
      e = Math.sqrt(b * b - h * h); // distance from C to center of rhombus
      // rhomubs is DBCE, D is top point, A is bottom point
      pos_neg = h > 0 ? 1 : -1;
      i = pos_neg * h;
      A = [0, 0];
      B = [0, d - i];
      C = [e, d];
      D = [0, d + i];
      E = [-e, d];
      Y = [a + c / 2, c];
      cos = c / (d + i);
      sin = Math.sqrt(1 - cos * cos) * pos_neg;
      rotate = function(point) {
        var x, y;
        [x, y] = point;
        return [x * cos + y * sin, y * cos - x * sin];
      };
      segment = function(color, point1, point2) {
        return canvas.segment(color, rescale(point1), rescale(point2));
      };
      show = function() {
        segment("pink", A, B);
        segment("blue", E, D);
        segment("blue", D, C);
        segment("blue", C, B);
        segment("blue", B, E);
        segment("green", A, E);
        return segment("green", A, C);
      };
      A = rotate(A);
      B = rotate(B);
      C = rotate(C);
      D = rotate(D);
      E = rotate(E);
      x_offset = 12;
      y_distort = 1;
      if (recording) {
        path1.push(B);
        path2.push(D);
        path3.push(C);
        path4.push(E);
      }
      ref = [path1, path2, path3, path4];
      for (j = 0, len = ref.length; j < len; j++) {
        path = ref[j];
        for (i = k = 0, ref1 = path.length - 1; (0 <= ref1 ? k < ref1 : k > ref1); i = 0 <= ref1 ? ++k : --k) {
          segment("pink", path[i], path[i + 1]);
        }
      }
      show();
      h += dh;
      if (h < -b || h > b) {
        if (h < 0) {
          recording = false;
        }
        dh *= -1;
        h += dh;
      }
      return setTimeout(draw, dt);
    };
    draw();
    button = get_div("#linkage_pause");
    return button.addEventListener("click", function() {
      if (paused) {
        paused = false;
        draw();
        return button.val("pause");
      } else {
        paused = true;
        return button.val("resume");
      }
    });
  };

  PythagFolding = function() {
    var A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, a, b, blue, canvas, draw_poly, height, i, j, k, rescale, results, segment, x_offset;
    x_offset = 50;
    height = 130;
    rescale = function(point) {
      var x, y;
      [x, y] = point;
      return [x * 10 + x_offset, height - y * 10 - 10];
    };
    canvas = Canvas(get_div("#pythag_fold1"), "pythag_fold1_canvas", 400, height);
    a = 8.5;
    b = 11;
    A = [0, 0];
    B = [0, b];
    C = [a, b];
    D = [a, 0];
    draw_poly = function(color, ...points) {
      var point, scaled_points;
      scaled_points = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = points.length; j < len; j++) {
          point = points[j];
          results.push(rescale(point));
        }
        return results;
      })();
      return canvas.draw_polygon(color, ...scaled_points);
    };
    segment = function(color, point1, point2) {
      return canvas.segment(color, rescale(point1), rescale(point2));
    };
    draw_poly("lightblue", A, B, C, D);
    x_offset += 120;
    D = [a * (a * a - b * b) / (a * a + b * b), a * (2 * a * b) / (a * a + b * b)];
    draw_poly("lightblue", A, B, C);
    draw_poly("red", A, D, C);
    segment("black", A, C);
    x_offset += 100;
    D = [a, 0];
    draw_poly("lightblue", A, B, C);
    draw_poly("lightblue", A, C, D);
    segment("blue", A, C);
    x_offset = 50;
    canvas = Canvas(get_div("#pythag_fold2"), "pythag_fold2_canvas", 800, height);
    draw_poly("lightblue", A, B, C);
    draw_poly("lightblue", A, C, D);
    segment("blue", A, C);
    x_offset += 100;
    E = [0, a];
    F = [a, a];
    draw_poly("lightblue", A, B, C, F);
    segment("blue", A, C);
    draw_poly("red", A, E, F);
    segment("black", A, F);
    segment("pink", E, F);
    x_offset += 100;
    G = [a, 2 * a - b];
    H = [0, 2 * a - b];
    K = [2 * a - b, 2 * a - b];
    draw_poly("lightblue", A, E, F);
    draw_poly("red", E, F, G, H);
    segment("black", E, F);
    segment("pink", H, K);
    x_offset += 100;
    L = [2 * a - b, a];
    draw_poly("lightblue", A, E, F);
    draw_poly("lightblue", E, F, K, H);
    draw_poly("red", L, K, F);
    segment("pink", H, K);
    segment("pink", L, K);
    segment("black", K, F);
    x_offset += 100;
    I = [3 * a - 2 * b, a];
    draw_poly("lightblue", A, H, K);
    draw_poly("lightblue", E, L, K, H);
    draw_poly("red", L, K, I);
    segment("pink", H, K);
    segment("pink", L, K);
    segment("pink", K, I);
    segment("black", K, L);
    x_offset += 100;
    J = [3 * a - 2 * b, 2 * a - b];
    draw_poly("lightblue", A, H, K);
    draw_poly("lightblue", E, I, K, H);
    draw_poly("red", J, K, I);
    segment("pink", H, K);
    segment("pink", I, J);
    segment("black", I, K);
    x_offset += 100;
    M = [2 * a - b, b];
    N = [a, 2 * a - b];
    O = [a, 3 * a - 2 * b];
    draw_poly("lightblue", A, B, C, D);
    segment("blue", A, C);
    segment("blue", A, F);
    segment("blue", E, F);
    segment("green", M, L);
    segment("blue", L, K);
    segment("green", K, N);
    segment("blue", I, K);
    segment("green", K, O);
    segment("green", I, M);
    segment("green", M, F);
    x_offset = 50;
    canvas = Canvas(get_div("#pythag_fold3"), "pythag_fold3_canvas", 600, height);
    for (i = j = 1; j <= 2; i = ++j) {
      draw_poly("lightgreen", A, B, C);
      draw_poly("yellow", A, C, D);
      segment("blue", A, C);
      x_offset += 100;
    }
    draw_poly("black", A, B, M, K, N, D);
    draw_poly("cyan", M, C, N, K);
    segment("blue", E, F);
    blue = "#AAAADD";
    results = [];
    for (i = k = 1; k <= 2; i = ++k) {
      x_offset += 100;
      D = [a, 0];
      P = [a * a / b, a];
      draw_poly(blue, A, P, F, D);
      draw_poly("lightblue", P, F, C);
      draw_poly("red", A, E, P);
      results.push(draw_poly("pink", E, B, C, P));
    }
    return results;
  };

  PythagProof = function() {
    var a, b, blue, c, canvas, draw_poly, points, redraw, rescale, triangles;
    canvas = Canvas(get_div("#pythag_proof"), "pythag_canvas", 350, 350);
    rescale = function(point) {
      var x, y;
      [x, y] = point;
      y -= 4;
      return [x * 10 + 150, -y * 10 + 170];
    };
    draw_poly = function(poly, color, points) {
      var coords, i;
      coords = (function() {
        var j, ref, results;
        results = [];
        for (i = j = 0, ref = poly.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
          results.push(points[poly.charAt(i)]);
        }
        return results;
      })();
      return canvas.draw_polygon(color, ...coords);
    };
    a = 8.5;
    b = 2.5;
    c = (a * b) / (a + b);
    points = {
      A: function() {
        return [-a, 0];
      },
      B: function() {
        return [-a - b, 0];
      },
      C: function() {
        return [-a, b + c];
      },
      D: function() {
        return [-a, b];
      },
      E: function() {
        return [-a - b, b];
      },
      F: function() {
        return [-a - b, a + b];
      },
      G: function() {
        return [-a, a + b];
      },
      H: function() {
        return [0, a + b];
      },
      I: function() {
        return [a, a + b];
      },
      J: function() {
        return [a + b, a + b];
      },
      K: function() {
        return [a + b, a];
      },
      L: function() {
        return [a, a];
      },
      M: function() {
        return [b, a + b];
      },
      N: function() {
        return [a + b, 2 * a + b];
      },
      O: function() {
        return [2 * a + b, a];
      },
      P: function() {
        return [a + b, c];
      },
      Q: function() {
        return [a, 0];
      },
      R: function() {
        return [a, -a];
      },
      S: function() {
        return [0, c - a];
      },
      T: function() {
        return [0, -a];
      },
      U: function() {
        return [0, 0];
      },
      V: function() {
        return [b, a + b + c];
      },
      W: function() {
        return [0, b];
      },
      X: function() {
        return [-b, -a];
      },
      Y: function() {
        return [-b, 0];
      }
    };
    blue = "#AAAADD";
    triangles = [
      ["EDAB",
      "cyan"],
      ["ECGF",
      "pink"],
      ["EDC",
      "lightblue"],
      ["AUG",
      "yellow"],
      ["UGH",
      "lightgreen"],
      
      ["STRQ",
      blue],
      ["UQS",
      "red"],
      
      ["HIQ",
      "lightgreen"],
      ["HMV",
      "lightblue"],
      ["VNJM",
      blue],
      ["NKO",
      "yellow"],
      ["OKP",
      "red"],
      ["LKPQ",
      "pink"],
      ["IJKL",
      "cyan"]
    ];
    redraw = function() {
      var color, j, len, point, scaled_points, segment, triangle, vertex, vertices;
      canvas.clear();
      scaled_points = {};
      for (vertex in points) {
        point = points[vertex];
        scaled_points[vertex] = rescale(point());
      }
      segment = function(segment, color) {
        var point1, point2;
        point1 = scaled_points[segment.charAt(0)];
        point2 = scaled_points[segment.charAt(1)];
        return canvas.segment(color, point1, point2);
      };
      for (j = 0, len = triangles.length; j < len; j++) {
        triangle = triangles[j];
        [vertices, color] = triangle;
        draw_poly(vertices, color, scaled_points);
      }
      // black > blue > green
      segment("EH", "black");
      segment("HQ", "black");
      segment("HN", "black");
      segment("NO", "black");
      segment("OQ", "black");
      segment("GU", "black");
      segment("BU", "blue");
      segment("UH", "blue");
      segment("HF", "blue");
      segment("FB", "blue");
      segment("QI", "blue");
      segment("NK", "blue");
      segment("ED", "orange");
      segment("DW", "green");
      segment("UQ", "green");
      segment("AG", "blue");
      segment("XY", "green");
      segment("XT", "orange");
      segment("XQ", "black");
      segment("TR", "green");
      segment("QR", "green");
      return segment("UT", "green");
    };
    return redraw();
  };

  TwelveTriangles = function() {
    var canvas, draw, draw_triangle, height, rescale, skew;
    canvas = Canvas(get_div("#twelve_triangles"), "twelve_triangles_canvas");
    skew = 0;
    height = 1;
    rescale = function(point) {
      var x, y;
      [x, y] = point;
      x -= 4; // keep centroid centered
      x += y * skew;
      x /= height;
      y *= height;
      return [x * 40 + 300, -y * 40 + 150];
    };
    draw_triangle = function(triangle, color, points) {
      var v0, v1, v2;
      v0 = triangle.charAt(0);
      v1 = triangle.charAt(1);
      v2 = triangle.charAt(2);
      return canvas.draw_polygon(color, points[v0], points[v1], points[v2]);
    };
    draw = function() {
      var points, redraw, triangles;
      points = {
        A: [0, 2],
        B: [2, 2],
        C: [6, 2],
        D: [3, 1],
        E: [0, 0],
        F: [4, 0],
        G: [6, 0],
        H: [3, -1],
        I: [0, -2],
        J: [2, -2],
        K: [6, -2]
      };
      triangles = [
        ["ABE",
        "red"],
        ["BED",
        "green"],
        ["BCD",
        "blue"],
        ["DEF",
        "blue"],
        ["DFC",
        "green"],
        ["CFG",
        "red"],
        
        ["EFH",
        "pink"],
        ["FHK",
        "lightgreen"],
        ["FGK",
        "lightblue"],
        ["EIJ",
        "lightblue"],
        ["EJH",
        "lightgreen"],
        ["JHK",
        "pink"]
      ];
      redraw = function() {
        var color, j, len, point, scaled_points, triangle, vertex, vertices;
        canvas.clear();
        scaled_points = {};
        for (vertex in points) {
          point = points[vertex];
          scaled_points[vertex] = rescale(point);
        }
        for (j = 0, len = triangles.length; j < len; j++) {
          triangle = triangles[j];
          [vertices, color] = triangle;
          draw_triangle(vertices, color, scaled_points);
        }
        vertices = (function() {
          var k, len1, ref, results;
          ref = ["E", "C", "K"];
          results = [];
          for (k = 0, len1 = ref.length; k < len1; k++) {
            vertex = ref[k];
            results.push(scaled_points[vertex]);
          }
          return results;
        })();
        return canvas.outline_triangle("black", ...vertices);
      };
      redraw();
      get_div("#more_skew").addEventListener("click", function() {
        skew += 0.2;
        return redraw();
      });
      get_div("#less_skew").addEventListener("click", function() {
        skew -= 0.2;
        return redraw();
      });
      get_div("#taller").addEventListener("click", function() {
        height += 0.1;
        return redraw();
      });
      return get_div("#wider").addEventListener("click", function() {
        height -= 0.1;
        return redraw();
      });
    };
    return draw();
  };

  (function() {
    get_div("body").style.width = 800;
    Linkage();
    PythagProof();
    PythagFolding();
    return TwelveTriangles();
  })();

}).call(this);
